name: Codecov
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Run rspec to generate code coverage
    runs-on: ubuntu-latest
steps:
    - uses: actions/checkout@master
    - name: Set up Ruby 2.7.1
      uses: actions/setup-ruby@v1
      with:
        version: 2.7.x
- name: Run test cases
      run: |
        bundle exec rspec
      env:
        CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}